### ISSUE TITLE
Showing errors on UI

### ISSUE THREAD

**Issue by rishikunnath2747** [cap-java/cds-feature-attachments#221]
I am part of the team that is developing the [SDM plugin](https://github.com/cap-java/sdm). We store attachments in SDM during upload of the attachment. But in case we get an error from SDM while uploading, we want to display an error on the UI. However we aren't able to do this. The error is thrown in the console, but not on the UI. 

We have tried using the messages api, and throwing a service exception. Could the problem be that errors are only displayed on UI after saving the entity?

**Comment by rishikunnath2747** [comment]
Hi @BraunMatthias as per your discussion with @rashmiangadi11 is there any update on this issue? Our understanding is that this is not an issue from the attachments plugin, in that case has an issue/ticket been raised with the concerned team? If so, could you share a link to the issue/ticket. Thanks

**Comment by BraunMatthias** [comment]
As discussed with [rashmiangadi11](https://github.com/rashmiangadi11), we follow up on this finding in the attachment feature. See [BLI](https://github.wdf.sap.corp/cds-java/home/issues/1724).
