### ISSUE TITLE
Support of Rename attachments feature in SDM Java Plugin

### ISSUE THREAD

**Issue by yashmeet29** [cap-java/cds-feature-attachments#226]
I am part of the team that is developing the [SDM plugin](https://github.com/cap-java/sdm). I am working on rename attachment feature for SDM Java plugin. Rename of the attachment in SDM repository should happen after entity is saved. I saw there is no specific rename attachment feature in cds-feature-attachments plugin. So I want to understand to support this feature in SDM plugin, do I need to add my rename implementation CreateAttachmentHandler & UpdateAttachmentHandler or there are other way too.
I am attaching a recording of similar feature from node-js SDM plugin.

https://github.com/user-attachments/assets/73506b85-fa8a-4e06-90b3-fb9e17774e19

Regards,
Yashmeet

**Comment by mofterdinger** [comment]
Hi, I'm currently integrating the [cds-feature-attachment](https://github.com/cap-java/cds-feature-attachments) into our [Bookshop sample application](https://github.com/SAP-samples/cloud-cap-samples-java/pull/377) and I can rename the filename as you can see on the following screenshot:

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/d9a6e17a-1be8-4ea7-bd1a-beb90a6066a7">

Sorry, I don't know your implementation, but maybe @BraunMatthias or @adamandre79  have an idea.

Thanks,
Markus

**Comment by mofterdinger** [comment]
@yashmeet29 Hi, is your SDM Plugin a copy of the cds-feature-attachment? I found that you are using your own CDS Model: https://github.com/cap-java/sdm/tree/develop/sdm/src/main/resources/cds/com.sap.cds/sdm 
with own UI annotations.

Please explain how is the relation of your plugin with the cds-feature-attachment.

Thanks,
Markus

**Comment by yashmeet29** [comment]
Hi @mofterdinger, no SDM plugin is not a copy of cds-feature-attachments rather it uses SAP Document Management Service as storage for attachments. So, basically it is the SDM flavour of attachments plugin. SDM plugin inherits most of the things from cds-feature-attachments. Actually in our cds models we needed some extra fields like repositoryId, folderId, url. So, we added other fields from cds-feature-attachments and added added fields too.

**Comment by adamandre79** [comment]
Hello @yashmeet29 ,

as discussed before, please do not copy the cds model and add you new fields, but use the cds model with all the annotations from the attachments plugin and only extend it with your fields.
See also my comment in: https://github.com/cap-java/cds-feature-attachments/issues/189#issuecomment-2374088633
After that is done you can discuss additional requirements with @BraunMatthias .

Regards
André
