### ISSUE TITLE
License risks in blackduck scans

### ISSUE THREAD

**Issue by yashmeet29** [cap-java/cds-feature-attachments#281]
Hi colleagues,
I was checking blackduck scan for SDM plugin & I see below mentioned License risks coming from libraries being used in cds-feature-attachments. All of these being Transitive dependencies.

Blackduck dashboard URL: [dashboard](https://sap.blackducksoftware.com/api/projects/04c7d92c-7b60-4493-a919-e9bb0f85e67f/versions/d9c6179c-9c93-4590-a77f-1f811d2a4bea/components?filter=bomInclusion%3Afalse&filter=bomMatchInclusion%3Afalse&filter=bomMatchReviewStatus%3Areviewed&filter=licenseRisk%3Amedium&filter=licenseRisk%3Alow&limit=100&offset=0)

- 3 medium severity License risks in "cds4j:jdbc-spi", "CDS Services Implementation" & "CDS Services Utils" libraries.
- 1 low severity License risks in jms library.

Attaching the screenshots from scan dashboard below:
<img width="1649" alt="Screenshot 2024-11-19 at 4 39 10 PM" src="https://github.com/user-attachments/assets/e6680aba-89e6-4ab0-9dd5-945859fa52cd">
<img width="1649" alt="Screenshot 2024-11-19 at 4 39 21 PM" src="https://github.com/user-attachments/assets/ae673403-c0b6-469c-85e9-3b8c7d6acdd3">
<img width="1649" alt="Screenshot 2024-11-19 at 4 39 27 PM" src="https://github.com/user-attachments/assets/9355ad1e-631b-4832-ad45-889ae67b46ad">
<img width="1649" alt="Screenshot 2024-11-19 at 4 42 07 PM" src="https://github.com/user-attachments/assets/f16ff5c5-7b17-4fd9-829f-0daac852ca7d">

**Comment by mofterdinger** [comment]
> 3 medium severity License risks in "cds4j:jdbc-spi", "CDS Services Implementation" & "CDS Services Utils" libraries.

This library is provided by CAP Java (SAP itself), so I don't see a license issue here. Looks like blackduck is not aware of this.

> 1 low severity License risks in jms library.

What is the issue with library ? I don't find any information in the provided screenshot. Can you provide more details about the license issue you got from blackjack.

**Comment by yashmeet29** [comment]
Hi Markus, I have added you to the blackduck dashboard portal. You can check [here](https://sap.blackducksoftware.com/api/projects/04c7d92c-7b60-4493-a919-e9bb0f85e67f/versions/d9c6179c-9c93-4590-a77f-1f811d2a4bea/components?filter=bomInclusion%3Afalse&filter=bomMatchInclusion%3Afalse&filter=bomMatchReviewStatus%3Areviewed&filter=licenseRisk%3Amedium&filter=licenseRisk%3Alow&limit=100&offset=0)

**Comment by yashmeet29** [comment]
@mofterdinger Any update on this?

**Comment by mofterdinger** [comment]
Still waiting your answer to my question:

> What is the issue with this library ? I don't find any information in the provided screenshot. Can you provide more details about the license issue you got from blackjack.

**Comment by yashmeet29** [comment]
I added you onto the dashboard [here](https://sap.blackducksoftware.com/api/projects/04c7d92c-7b60-4493-a919-e9bb0f85e67f/versions/d9c6179c-9c93-4590-a77f-1f811d2a4bea/components?filter=bomInclusion%3Afalse&filter=bomMatchInclusion%3Afalse&filter=bomMatchReviewStatus%3Areviewed&filter=licenseRisk%3Amedium&filter=licenseRisk%3Alow&limit=100&offset=0). You can check there as well. Also, I am attaching the screenshots from the portal. Looks like there is some issue with the license of these libraries.

<img width="1649" alt="Screenshot 2024-11-22 at 3 38 42 PM" src="https://github.com/user-attachments/assets/02f5ffea-e6f7-485d-9d7f-139fdadade86">
<img width="1649" alt="Screenshot 2024-11-22 at 3 38 28 PM" src="https://github.com/user-attachments/assets/5ad9e8e4-13e9-4ede-ac8a-ec4cd62d67ce">
<img width="1649" alt="Screenshot 2024-11-22 at 3 38 15 PM" src="https://github.com/user-attachments/assets/04a2ef40-a0a6-4d2d-a5a1-0e3ed800ea52">

<img width="1649" alt="Screenshot 2024-11-22 at 3 36 10 PM" src="https://github.com/user-attachments/assets/6910bfcf-4e97-4f93-8a9b-f76f1d1fd3c0">

**Comment by mofterdinger** [comment]
@michael-hellenschmidt Hi Michael, can you please have a look at this blackduck issues from the SDM colleagues ?

Thanks,
Markus

**Comment by mofterdinger** [comment]
Hi, as discussed in one of our past weekly sync meetings, this is not an issue. All mentioned artifacts are either provided by SAP itself or transitive dependency of them.
